[project]
name = "jungle-beans-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.3",
    "waitress>=3.0.2",
]

[project.scripts]
jungle-beans-game = "jungle_beans_game:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
